### ISSUE TITLE
Model fit error

### ISSUE THREAD

**Issue by thisislohith6** [rezachu/emotion_recognition_cnn#11]
Hi, I found your approach very interesting and useful for me. I am trying to implement the code but I was facing an error as below mentioned. So, could you please help me with this.

Thanks in Advance, Appreciate your help!

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv1d (Conv1D)              (None, 259, 256)          2304      
_________________________________________________________________
activation (Activation)      (None, 259, 256)          0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 259, 256)          524544    
_________________________________________________________________
batch_normalization (BatchNo (None, 259, 256)          1024      
_________________________________________________________________
activation_1 (Activation)    (None, 259, 256)          0         
_________________________________________________________________
dropout (Dropout)            (None, 259, 256)          0         
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 32, 256)           0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, 32, 128)           262272    
_________________________________________________________________
activation_2 (Activation)    (None, 32, 128)           0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 32, 128)           131200    
_________________________________________________________________
activation_3 (Activation)    (None, 32, 128)           0         
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 32, 128)           131200    
_________________________________________________________________
activation_4 (Activation)    (None, 32, 128)           0         
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 32, 128)           131200    
_________________________________________________________________
batch_normalization_1 (Batch (None, 32, 128)           512       
_________________________________________________________________
activation_5 (Activation)    (None, 32, 128)           0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 32, 128)           0         
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 4, 128)            0         
_________________________________________________________________
conv1d_6 (Conv1D)            (None, 4, 64)             65600     
_________________________________________________________________
activation_6 (Activation)    (None, 4, 64)             0         
_________________________________________________________________
conv1d_7 (Conv1D)            (None, 4, 64)             32832     
_________________________________________________________________
activation_7 (Activation)    (None, 4, 64)             0         
_________________________________________________________________
flatten (Flatten)            (None, 256)               0         
_________________________________________________________________
dense (Dense)                (None, 2)                 514       
_________________________________________________________________
activation_8 (Activation)    (None, 2)                 0         
=================================================================
Total params: 1,283,202
Trainable params: 1,282,434
Non-trainable params: 768
_________________________________________________________________
**Epoch 1/700
Traceback (most recent call last):
  File "C:/Users/Lohith/PycharmProjects/speech-2/cnn.py", line 888, in <module>
    validation_data=(x_testcnn, y_test), callbacks=[mcp_save, lr_reduce])**
  File "C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 697, in _initialize
    *args, **kwds))
  File "C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\eager\function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    C:/Users/850047682/PycharmProjects/speech-2/cnn.py:787 fscore  *
        if K.sum(K.round(K.clip(y_true, 0, 1))) == 0:
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\autograph\operators\control_flow.py:951 if_stmt
        _tf_if_stmt(cond, body, orelse, get_state, set_state, symbol_names, nouts)
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\autograph\operators\control_flow.py:996 _tf_if_stmt
        cond, aug_body, aug_orelse, strict=True)
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\util\dispatch.py:201 wrapper
        return target(*args, **kwargs)
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\util\deprecation.py:507 new_func
        return func(*args, **kwargs)
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py:1180 cond
        return cond_v2.cond_v2(pred, true_fn, false_fn, name)
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\ops\cond_v2.py:92 cond_v2
        op_return_value=pred)
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\framework\func_graph.py:986 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\autograph\operators\control_flow.py:992 aug_orelse
        _verify_tf_cond_vars(new_body_vars_[0], new_orelse_vars, symbol_names)
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\autograph\operators\control_flow.py:288 _verify_tf_cond_vars
        functools.partial(verify_single_cond_var, name), body_var, orelse_var)
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\util\nest.py:635 map_structure
        structure[0], [func(*x) for x in entries],
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\util\nest.py:635 <listcomp>
        structure[0], [func(*x) for x in entries],
    C:\Users\850047682\PycharmProjects\speech-2\venv\lib\site-packages\tensorflow\python\autograph\operators\control_flow.py:260 verify_single_cond_var
        orelse_var.dtype.name))

    **TypeError: 'retval_' has dtype int32 in the main branch, but dtype float32 in the else branch**

**Comment by littleBuddhaa** [comment]
@thisislohith6 were you able to resolve this
